name: SDF Validation
run-name: validate

on: [push]

jobs:
  sdf-validate:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      # Step 1: Checkout repository
      - name: Check out repository code
        uses: actions/checkout@v3

      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Step 3: Install JDK
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      # Step 4: Install npm dependencies
      - name: Install dependencies
        run: npm ci --acceptsuitecloudsdklicense

      # Step 5: Run unit tests
      - name: Run unit tests
        run: npm test

      - name: Install SuiteCloud CLI
        run: npm i -g @oracle/suitecloud-cli@latest --acceptSuiteCloudSDKLicense
      - name: Configure SuiteCloud CI auth (OAuth2)
        env:
          NS_ACCOUNT: 4541795_SB1
          NS_ROLE: 3
          NS_DOMAIN:  https://system.netsuite.com
          OAUTH_CLIENT_ID:     ${{ secrets.NS_TOKEN_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.NS_TOKEN_SECRET }}
        run: |
          suitecloud account:setup:ci \
            --authid SANDBOX \
            --account "$NS_ACCOUNT" \
            --role "$NS_ROLE" \
            --url "$NS_DOMAIN" \
            --client "$OAUTH_CLIENT_ID" \
            --secret "$OAUTH_CLIENT_SECRET"
